% A demo of dtw
% to demo the funtion dtw.m
% The data is generated by Gauss distribution
% with different averag
%
% Jingchang Liu
% 2016/04/11

%% gernerate sequence Q && C
% M: the length of Q
% N: the length of C
% w: window parameter
M = 10000; N = 12000;
Q = normrnd(0,1,M,1);
C = normrnd(1,1,N,1);
w = 1000;

tic;
d=dtw(Q,C,w);
t=toc;

fprintf('distance=%f, running time=%f\n',d,t);