% A realization of DTW algorithm
% there is limit of locality constraint in this version
% The data is generated by Gauss distribution
% with different averag
%
% Jingchang Liu
% 2016/04/11

%% gernerate sequence Q && C
% M: the length of Q
% N: the length of C
% w: window parameter
M = 1000; N = 1200;
Q = normrnd(0,1,M,1);
C = normrnd(1,1,N,1);
w = 100;

%% initialize DTW
% DTW(i+1,j+1): The accumulated distance between
%   Q(1) to Q(i) and C(1) to C(j)
DTW = zeros(M+1,N+1);
w = max([w,abs(M-N)]);

for i = 2:M+1
    for j =2:N+1
        DTW(i,j) = inf;
    end
end
DTW(1,1) = 0;

%% DTW algorithm
% d(i,j):The distance between Q(i) and C(j)
for i = 2:M+1
    for j = max([2,i-w+1]) : min([N+1,i+w+1])
        d = norm(Q(i-1)-C(j-1));
        DTW(i,j) = d+ min([DTW(i-1,j),DTW(i,j-1),DTW(i-1,j-1)]);
    end
end
