% A realization of DTW algorithm
% there is no limit of locality constraint in this version
% The data is generated by Gauss distribution
% with different average
% Jingchang Liu
% 2016/04/11

%% gernerate sequence Q && C
% M: the length of Q
% N: the length of C
M = 1000; N = 1200;
Q = normrnd(0,1,M,1);
C = normrnd(1,1,N,1);

%% initialize DTW
% DTW(i+1,j+1): The accumulated distance between
%   Q(1) to Q(i) and C(1) to C(j)
DTW = zeros(M+1,N+1);

for i = 2:M+1
    DTW(i,1) = inf;
end
for i = 2:N+1
    DTW(1,i) = inf;
end
DTW(1,1) = 0;

%% DTW algorithm
% d(i,j):The distance between Q(i) and C(j)
for i = 2:M+1
    for j = 2:N+1
        d = norm(Q(i-1)-C(j-1));
        DTW(i,j) = d+ min([DTW(i-1,j),DTW(i,j-1),DTW(i-1,j-1)]);
    end
end
